export const getDeviceApi = () => {
	return {
		canIUse: uni.canIUse,
		showNavigationBarLoading: uni.showNavigationBarLoading,
		hideNavigationBarLoading: uni.hideNavigationBarLoading,
		stopPullDownRefresh: uni.stopPullDownRefresh,
		chooseImage: uni.chooseImage,
		getStorage: uni.getStorage,
		getStorageSync: uni.getStorageSync,
		getImageInfo: uni.getImageInfo,
		setStorageSync: uni.setStorageSync,
		clearStorage: uni.clearStorage,
		removeStorageSync: uni.removeStorageSync,
		navigateTo: uni.navigateTo,
		switchTab: uni.switchTab,
		reLaunch: uni.reLaunch,
		navigateBack: uni.navigateBack,
		showLoading: uni.showLoading,
		hideLoading: uni.hideLoading,
		showToast: uni.showToast,
		showModal: uni.showModal,
		showActionSheet: uni.showActionSheet,
		getSetting: uni.getSetting,
		authorize: uni.authorize,
		getNetworkType: uni.getNetworkType,
		openSetting: uni.openSetting,
		getSystemInfo: uni.getSystemInfo,
		getLocation: uni.getLocation,
		openLocation: uni.openLocation,
		redirectTo: uni.redirectTo,
		showShareMenu: uni.showShareMenu,
		onShareAppMessage: uni.onShareAppMessage,
		getSystemInfoSync: uni.getSystemInfoSync,
		makePhoneCall: uni.makePhoneCall,
		pageScrollTo: uni.pageScrollTo,
		requestPayment: uni.requestPayment,
		setNavigationBarTitle:uni.setNavigationBarTitle,
		getProvider: uni.getProvider,   // app-plus 上面获取是否有安装 微信、qq、微博等， provider 的值 "weixin"、 "qq"、"sinaweibo"、"xiaomi" 
		checkSession: uni.checkSession, // 监测微信登录状态
		getUserInfo:uni.getUserInfo,
		login: uni.login,
		getShareInfo: uni.getShareInfo
	}
} 